apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: dynamic-auth
  namespace: demo-ns
spec:
  method: kubernetes
  mount: demo-auth-mount
  kubernetes:
    role: auth-role-new
    serviceAccount: default
    audiences:
      - vault